apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: octdevteam2/backend
        name: backend
        ports:
          - containerPort: 9966

---

apiVersion: v1
kind: Service
metadata:
   name: backend
   labels:
     app: backend      
spec:
   type: ClusterIP
   ports:
     - protocol: TCP
       port: 9966
       targetPort: 9966
   selector:
     app: backend

