apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: octdevteam2/pet-db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: petclinic
        ports:
        - containerPort: 3306 
