apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts: 
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes: 
      - name: nginx-conf
        configMap:
          name: nginx-conf


---

apiVersion: v1
kind: Service
metadata:
   name: nginx
   labels:
     app: nginx   
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   selector:
     app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-conf
data:
  default.conf: |
    server {
            listen 80;
            location / {
                    proxy_pass http://frontend:4200;
            }
            location /petclinic/api {
                    proxy_pass http://backend:9966;
            }
             }
